//PACKAGE COM.INCTURE.CHERRYWORK.SERVICES;
//
//
//
//IMPORT JAVA.IO.FILE;
//IMPORT JAVA.IO.FILEOUTPUTSTREAM;
//IMPORT JAVA.UTIL.ARRAYLIST;
//IMPORT JAVA.UTIL.BASE64;
//IMPORT JAVA.UTIL.LIST;
//IMPORT JAVA.UTIL.UUID;
//
//IMPORT JAVAX.TRANSACTION.TRANSACTIONAL;
//
//IMPORT ORG.SLF4J.LOGGER;
//IMPORT ORG.SLF4J.LOGGERFACTORY;
//IMPORT ORG.SPRINGFRAMEWORK.BEANS.FACTORY.ANNOTATION.AUTOWIRED;
//IMPORT ORG.SPRINGFRAMEWORK.HTTP.HTTPMETHOD;
//IMPORT ORG.SPRINGFRAMEWORK.STEREOTYPE.SERVICE;
//IMPORT ORG.SPRINGFRAMEWORK.WEB.MULTIPART.COMMONS.COMMONSMULTIPARTFILE;
//
//IMPORT COM.INCTURE.CHERRYWORK.DTOS.ATTACHMENTDTO;
//IMPORT COM.INCTURE.CHERRYWORK.DTOS.RESPONSEDTO;
//IMPORT COM.INCTURE.CHERRYWORK.ENTITIES.ATTACHMENTDO;
//IMPORT COM.INCTURE.CHERRYWORK.REPOSITORIES.ATTACHMENTREPO;
//IMPORT COM.INCTURE.CHERRYWORK.UTIL.OBJECTSTOREUTIL;
//
//
//
//@SERVICE
//@TRANSACTIONAL
//PUBLIC CLASS DOCUMENTMODELSERVICEIMPL IMPLEMENTS DOCUMENTMODELSERVICE {
//
//	PRIVATE FINAL LOGGER LOGGER = LOGGERFACTORY.GETLOGGER(THIS.GETCLASS());
//
//	@AUTOWIRED
//	PRIVATE SHAREPOINTSERVICE SHAREPOINTSERVICE;
//
//	@AUTOWIRED
//	PRIVATE ATTACHMENTREPO ATTACHMENTREPO;
//
//	@AUTOWIRED
//	PRIVATE OBJECTSTORESERVICE OBJECTSTORESERVICE;
//
//	PUBLIC RESPONSEDTO UPLOADDOCUMENT(STRING ENTITYID, STRING ENTITYTYPE, COMMONSMULTIPARTFILE FILE) {
//		RESPONSEDTO RESPONSEDTO = NEW RESPONSEDTO();
//		ATTACHMENTDTO ATTACHMENTDTO = NULL;
//
//		TRY {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.TRUE);
//			RESPONSEDTO.SETSTATUSCODE(200);
//
//			ATTACHMENTDTO = NEW ATTACHMENTDTO();
//			ATTACHMENTDTO.SETENTITYID(ENTITYID);
//			ATTACHMENTDTO.SETENTITYTYPE(ENTITYTYPE);
//			ATTACHMENTDTO.SETDOCUMENTID(UUID.RANDOMUUID().TOSTRING().REPLACE("-", ""));
//			ATTACHMENTDTO.SETCONTENT(FILE.GETBYTES());
//			ATTACHMENTDTO.SETDOCUMENTNAME(FILE.GETORIGINALFILENAME().TRIM().REPLACE(" ", ""));
//			ATTACHMENTDTO.SETFILECONTENT(NEW STRING(FILE.GETBYTES()));
//SYSTEM.ERR.PRINTLN("HELLO");
//			SHAREPOINTSERVICE.ATTACHFILE("HTTPS://INCTURET.SHAREPOINT.COM/SITES/CHERRYWORKS-COLLABORATIVEORDERMANAGEMENT-IND00120673/"
//					+ "GETFOLDERBYSERVERRELATIVEURL(%27SHARED%20DOCUMENTS/FORMS%27)/ADD(URL=%27"
//					+ ATTACHMENTDTO.GETDOCUMENTNAME() + "%27,OVERWRITE=FALSE)", ATTACHMENTDTO.GETCONTENT());
//			SYSTEM.ERR.PRINTLN("HELLO1");
//			ATTACHMENTREPO.SAVE(ATTACHMENTREPO.IMPORTDTO(ATTACHMENTDTO));
//
//			RESPONSEDTO.SETMESSAGE("FILE UPLOADED SUCCESSFULLY !");
//
//		} CATCH (EXCEPTION E) {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.FALSE);
//			RESPONSEDTO.SETSTATUSCODE(500);
//			RESPONSEDTO.SETMESSAGE(E.GETMESSAGE());
//		}
//		RETURN RESPONSEDTO;
//	}
//
//	@OVERRIDE
//	PUBLIC RESPONSEDTO GETDOCUMENTBYID(STRING DOCUMENTID) {
//		RESPONSEDTO RESPONSEDTO = NEW RESPONSEDTO();
//
//		TRY {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.TRUE);
//			RESPONSEDTO.SETSTATUSCODE(200);
//
//			ATTACHMENTDO ATTACHMENTDO = ATTACHMENTREPO.GETATTACHMENTDETAILSBYID(DOCUMENTID);
//			IF (ATTACHMENTDO != NULL) {
//				ATTACHMENTDTO ATTACHMENT = ATTACHMENTREPO.EXPORTDTO(ATTACHMENTDO);
//				BYTE[] ORIGINALDOC = SHAREPOINTSERVICE.PERFORMHTTPREQUEST(HTTPMETHOD.GET,
//						"HTTPS://INCTURET.SHAREPOINT.COM/SITES/CHERRYWORKS-COLLABORATIVEORDERMANAGEMENT-IND00120673/SHARED%20DOCUMENTS/FORMS/"
//								+ ATTACHMENTDO.GETDOCUMENTNAME());
//				BYTE[] ENCODED = BASE64.GETENCODER().ENCODE(ORIGINALDOC);
//				ATTACHMENT.SETFILECONTENT(NEW STRING(ENCODED));
//				RESPONSEDTO.SETDATA(ATTACHMENT);
//			}
//		} CATCH (EXCEPTION E) {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.FALSE);
//			RESPONSEDTO.SETSTATUSCODE(500);
//			RESPONSEDTO.SETMESSAGE(E.GETMESSAGE());
//		}
//		RETURN RESPONSEDTO;
//	}
//
//	@OVERRIDE
//	PUBLIC RESPONSEDTO GETATTACHMENTSBYENTITY(STRING ENTITYID, STRING ENTITYTYPE) {
//		RESPONSEDTO RESPONSEDTO = NEW RESPONSEDTO();
//
//		TRY {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.TRUE);
//			RESPONSEDTO.SETSTATUSCODE(200);
//
//			// LIST<ATTACHMENTDO> ATTACHMENTDOLIST =
//			// ATTACHMENTREPO.GETATTACHMENTBYENTITY(ENTITYID, ENTITYTYPE);
//			LIST<OBJECT[]> ATTACHMENTDOLIST = ATTACHMENTREPO.GETATTACHMENTBYENTITY(ENTITYID, ENTITYTYPE);
//			IF (ATTACHMENTDOLIST != NULL && !ATTACHMENTDOLIST.ISEMPTY()) {
//				LOGGER.ERROR("ATTACHMENTDTOLIST = " + ATTACHMENTDOLIST.TOSTRING());
//
//				LIST<ATTACHMENTDTO> ATTACHMENTDTOLIST = NEW ARRAYLIST<>();
//				
//				// * FOR (ATTACHMENTDO ENTITY : ATTACHMENTDOLIST) {
//				// * ATTACHMENTDTOLIST.ADD(ATTACHMENTREPO.EXPORTDTO(ENTITY)); }
//				 
//
//				FOR (OBJECT[] OBJ : ATTACHMENTDOLIST) {
//					ATTACHMENTDTO ATTACHMENT = NEW ATTACHMENTDTO();
//					ATTACHMENT.SETDOCUMENTID((OBJ[0] != NULL) ? (STRING) OBJ[0] : NULL);
//					ATTACHMENT.SETDOCUMENTNAME((OBJ[1] != NULL) ? (STRING) OBJ[1] : NULL);
//					ATTACHMENT.SETENTITYID((OBJ[2] != NULL) ? (STRING) OBJ[2] : NULL);
//					ATTACHMENT.SETENTITYTYPE((OBJ[3] != NULL) ? (STRING) OBJ[3] : NULL);
//					ATTACHMENT.SETCONTENTTYPE((OBJ[4] != NULL) ? (STRING) OBJ[4] : NULL);
//					ATTACHMENTDTOLIST.ADD(ATTACHMENT);
//				}
//				RESPONSEDTO.SETDATA(ATTACHMENTDTOLIST);
//				LOGGER.ERROR("ATTACHMENTDTOLIST = " + ATTACHMENTDTOLIST);
//				RESPONSEDTO.SETMESSAGE("ATTACHMENTS FETCHED SUCCESSFULLY!");
//			}
//		} CATCH (EXCEPTION E) {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.FALSE);
//			RESPONSEDTO.SETSTATUSCODE(500);
//			RESPONSEDTO.SETMESSAGE(E.GETMESSAGE());
//		}
//		RETURN RESPONSEDTO;
//	}
//
//	@OVERRIDE
//	PUBLIC VOID SAVEATTACHMENTS(LIST<ATTACHMENTDTO> LIST) {
//		FOR (ATTACHMENTDTO DTO : LIST) {
//			ATTACHMENTREPO.SAVE(ATTACHMENTREPO.IMPORTDTO(DTO));
//		}
//	}
//
//	@OVERRIDE
//	PUBLIC VOID DELETEATTATCHMENT(STRING DOCUMENTID, STRING FILENAME) {
//		ATTACHMENTREPO.DELETEBYATTACHMENT(DOCUMENTID);
//	}
//
//	@OVERRIDE
//	PUBLIC ATTACHMENTDTO GETATTACHMENTSBYDOCMENTID(STRING DOCUMENTID) {
//		RETURN ATTACHMENTREPO.EXPORTDTO(ATTACHMENTREPO.FINDBYDOCUMENTID(DOCUMENTID));
//	}
//
//	
//
//	
//	@OVERRIDE
//	PUBLIC RESPONSEDTO UPLOADDOCUMENTTOSTORE(STRING ENTITYID, STRING ENTITYTYPE, COMMONSMULTIPARTFILE[] FILES) {
//		RESPONSEDTO RESPONSEDTO = NEW RESPONSEDTO();
//SYSTEM.ERR.PRINTLN("HELLO1");
//		TRY {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.TRUE);
//			RESPONSEDTO.SETSTATUSCODE(200);
//			RESPONSEDTO.SETMESSAGE("FILE UPLOADED SUCCESSFULLY !");
//			LIST<ATTACHMENTDTO> LIST = NEW ARRAYLIST<>();
//
//			BYTE[] BYTEARRAY = NULL;
//			STRINGBUFFER MESSAGE = NEW STRINGBUFFER();
//			SYSTEM.ERR.PRINTLN("HELLO2");
//
//			FOR (COMMONSMULTIPARTFILE FILE : FILES) {
//				ATTACHMENTDTO ATTACHMENTDTO = NEW ATTACHMENTDTO();
//				IF (!FILE.ISEMPTY()) {
//					FILE CONVFILE = NEW FILE(FILE.GETORIGINALFILENAME());
//					CONVFILE.CREATENEWFILE();
//				FILEOUTPUTSTREAM FOS = NEW FILEOUTPUTSTREAM(CONVFILE);
//					FOS.WRITE(FILE.GETBYTES());					FOS.CLOSE();
//					BYTEARRAY = FILE.GETBYTES();
//					SYSTEM.ERR.PRINTLN("HELLO3");
//					FINAL STRING CONTENTTYPE = FILE.GETCONTENTTYPE();
//					ATTACHMENTDTO.SETENTITYID(ENTITYID);
//					ATTACHMENTDTO.SETENTITYTYPE(ENTITYTYPE);
//					ATTACHMENTDTO.SETDOCUMENTID(UUID.RANDOMUUID().TOSTRING().REPLACE("-", ""));
//				ATTACHMENTDTO.SETDOCUMENTNAME(FILE.GETORIGINALFILENAME());
//					ATTACHMENTDTO.SETCONTENTTYPE(FILE.GETCONTENTTYPE());
//					// ATTACHMENTDTO.SETFILECONTENT(NEW STRING(BYTEARRAY));
//					SYSTEM.ERR.PRINTLN("HELLO4");
//					MESSAGE.APPEND(OBJECTSTORESERVICE.UPLOADFILE(BYTEARRAY,
//							ATTACHMENTDTO.GETDOCUMENTID() + "_" + FILE.GETORIGINALFILENAME(), CONTENTTYPE));
//					LIST.ADD(ATTACHMENTDTO);
//				}
//	}			IF (LIST != NULL && !LIST.ISEMPTY())
//	{				SAVEATTACHMENTS(LIST);			}
//	
//		} CATCH (EXCEPTION E) {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.FALSE);
//			RESPONSEDTO.SETSTATUSCODE(500);
//			RESPONSEDTO.SETMESSAGE(E.GETMESSAGE());
//		}
//		RETURN RESPONSEDTO;
//	}
//
//	
//	@OVERRIDE
//	PUBLIC RESPONSEDTO DELETEFILEBYDOCUMENTID(STRING DOCUMENTID) {
//		RESPONSEDTO RESPONSEDTO = NEW RESPONSEDTO();
//
//		TRY {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.TRUE);
//			RESPONSEDTO.SETSTATUSCODE(200);
//			RESPONSEDTO.SETMESSAGE(OBJECTSTOREUTIL.CANNOT_DELETE_NULL);
//
//			ATTACHMENTDTO ATTACHMENTDTO = GETATTACHMENTSBYDOCMENTID(DOCUMENTID);
//			IF (ATTACHMENTDTO != NULL) {
//				IF (ATTACHMENTDTO.GETDOCUMENTNAME() != NULL) {
//					IF (THIS.OBJECTSTORESERVICE
//							.ISBLOBEXIST(ATTACHMENTDTO.GETDOCUMENTID() + "_" + ATTACHMENTDTO.GETDOCUMENTNAME())) {
//						IF (THIS.OBJECTSTORESERVICE
//								.DELETEFILE(ATTACHMENTDTO.GETDOCUMENTID() + "_" + ATTACHMENTDTO.GETDOCUMENTNAME())) {
//							RESPONSEDTO.SETMESSAGE(
//									ATTACHMENTDTO.GETDOCUMENTNAME() + " " + OBJECTSTOREUTIL.DELETE_SUCCESSFUL);
//						} ELSE {
//							RESPONSEDTO.SETMESSAGE(OBJECTSTOREUTIL.DELETE_FAILED + ATTACHMENTDTO.GETDOCUMENTNAME());
//						}
//					} ELSE {
//						RESPONSEDTO
//								.SETMESSAGE(ATTACHMENTDTO.GETDOCUMENTNAME() + " " + OBJECTSTOREUTIL.FILE_DOESNOT_EXIST);
//					}
//
//				}
//				DELETEATTATCHMENT(DOCUMENTID, ATTACHMENTDTO.GETDOCUMENTNAME());
//			} ELSE {
//				RESPONSEDTO.SETMESSAGE(OBJECTSTOREUTIL.FILE_DOESNOT_EXIST);
//			}
//		} CATCH (EXCEPTION E) {
//			RESPONSEDTO.SETSTATUS(BOOLEAN.FALSE);
//			RESPONSEDTO.SETSTATUSCODE(500);
//			RESPONSEDTO.SETMESSAGE(E.GETMESSAGE());
//		}
//		RETURN RESPONSEDTO;
//	}
//}
